// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriQerniOGktP-UCo6H88CY42KcvtHlL0',
    appId: '1:201490719302:web:cf5b8d2205469978896047',
    messagingSenderId: '201490719302',
    projectId: 'note67-shop',
    authDomain: 'note67-shop.firebaseapp.com',
    storageBucket: 'note67-shop.firebasestorage.app',
    measurementId: 'G-0WQEJ3L0F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4wDwFO9BB06laSe9wcF_pqD_XjH1_zI',
    appId: '1:201490719302:android:ba6d8d9f58af5426896047',
    messagingSenderId: '201490719302',
    projectId: 'note67-shop',
    storageBucket: 'note67-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGiGoDZdBi8hSglrlXX1xUSOErqIif1-w',
    appId: '1:201490719302:ios:4f53b4e926ef9bcb896047',
    messagingSenderId: '201490719302',
    projectId: 'note67-shop',
    storageBucket: 'note67-shop.firebasestorage.app',
    iosBundleId: 'com.example.thanawitproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGiGoDZdBi8hSglrlXX1xUSOErqIif1-w',
    appId: '1:201490719302:ios:4f53b4e926ef9bcb896047',
    messagingSenderId: '201490719302',
    projectId: 'note67-shop',
    storageBucket: 'note67-shop.firebasestorage.app',
    iosBundleId: 'com.example.thanawitproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBriQerniOGktP-UCo6H88CY42KcvtHlL0',
    appId: '1:201490719302:web:82d4626af22fa0af896047',
    messagingSenderId: '201490719302',
    projectId: 'note67-shop',
    authDomain: 'note67-shop.firebaseapp.com',
    storageBucket: 'note67-shop.firebasestorage.app',
    measurementId: 'G-Q39W2RQV3Z',
  );

}